version: '3.3'

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
    - ./nginx-config/:/etc/nginx/
    networks:
    - monitoring
    ports:
      - 80:80
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
    - ./prometheus-config/:/etc/prometheus/
    - ./prometheus-config/data/:/etc/prometheus/data/
    - ./prometheus-config/data/wal:/etc/prometheus/data/wal
    - ./prometheus-data:/var/lib/prometheus
    networks:
    - monitoring
    ports:
      - 9090:9090
  node-exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    networks:
    - monitoring
    ports:
      - 9100:9100
  alertmanager:
    image: prom/alertmanager
    #volumes:
    #  - ./alertmanager-config/:/etc/alertmanager/
    networks:
      - monitoring
    ports:
      - 9093:9093 
  grafana:
    image: grafana/grafana
    #image: nopp/grafana_alpine
    depends_on:
      - prometheus
    volumes:
      - ./grafana-config/grafana.db:/grafana/data/grafana.db
    #env_file:
    #  - grafana.env
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=easynvest
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel,camptocamp-prometheus-alertmanager-datasource,vonage-status-panel
    networks:
      - monitoring
    ports:
      - 3000:3000
  cadvisor:
    image: google/cadvisor
    hostname: '{{.Node.ID}}'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
        #   - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - monitoring
    deploy:
      mode: global
    ports:
      - 8080:8080
  netdata:
    image: netdata/netdata
    container_name: netdata
    volumes: 
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 19999:19999
networks:
  monitoring:
    external: true        
